version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: ree-mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hackeable